### ISSUE TITLE
Video not found

### ISSUE THREAD

**Issue by iCeY3** [jerry08/AniStream#2]
![Screenshot_20220626-072120_AniStream](https://user-images.githubusercontent.com/98146929/175799290-12f1c687-2b4b-475c-ab3b-8245be55078e.jpg)

**Comment by jerry08** [comment]
What anime is that? Maybe it happens for that specific anime. Let me know so I can test it and cater a workaround.

**Comment by jerry08** [comment]
What anime is that? Maybe it happens for that specific anime. Let me know so I can test it and cater a workaround.

**Comment by iCeY3** [comment]
I multiple animes more than 10

**Comment by jerry08** [comment]
Does it work for some animes? Give me an example of one anime it's not working for.

**Comment by iCeY3** [comment]
![Screenshot_20220626-231417_AniStream](https://user-images.githubusercontent.com/98146929/175832243-dc9fa53f-14f7-424b-8b68-754655fc0e5f.jpg)
![Screenshot_20220626-231407_AniStream](https://user-images.githubusercontent.com/98146929/175832246-853daf4e-f018-4613-b803-3ddd44b9b05f.jpg)

**Comment by jerry08** [comment]
![Screenshot_20220626-161735_AniStream](https://user-images.githubusercontent.com/74879119/175832476-9ffaa9e8-2c84-49b8-b1ac-84dd0c607994.jpg)
![Screenshot_20220626-161933_AniStream](https://user-images.githubusercontent.com/74879119/175832477-993f8259-fdef-4399-877d-18211c80bc0f.jpg)

It's working fine for me bro

**Comment by jerry08** [comment]
I honestly don't know why it's not working for you :')

**Comment by jerry08** [comment]
I was planning to add a feature to allow changing to different anime sites since my [AnimeDl](https://github.com/jerry08/AnimeDl) project already supports a few other sites. I will add the feature as soon as I have time.

**Comment by jerry08** [comment]
I posted an update so it might work now. If it doesn't, you can switch to different sites in the app.
