### ISSUE TITLE
Error when reproducing zoro.to(aniwatch) servers

### ISSUE THREAD

**Issue by olimpa** [jerry08/AniStream#22]
The catalog comes out, however it doesn't play the videos come out empty and it sends an error and the app closes.
![Screenshot_20230728-160511_AniStream](https://github.com/jerry08/AniStream/assets/36779899/de3c1955-ebf0-49d2-863d-2166336f07ec)
![Screenshot_20230728-160518_AniStream](https://github.com/jerry08/AniStream/assets/36779899/0e7b72c7-6538-4c64-a65e-4ac1e860fc17)

![Screenshot_20230728-160714_AniStream](https://github.com/jerry08/AniStream/assets/36779899/3c4d11d5-201d-47b7-af9f-ef0a4ac097c3)

**Comment by jerry08** [comment]
I'm aware of the bug and currently working on a fix for it. I'll post an update soon with the fixes.
