### ISSUE TITLE
App crashing consistently

### ISSUE THREAD

**Issue by 0r1ce** [jerry08/AniStream#27]
First of all the app is amazing, but whenever i try to play any episode it crashes after about a minute of play time, and after that doesnt let me open any details of any show.

**Comment by jerry08** [comment]
I can't replicate that issue you're experiencing. Does it happen for specific sites/sources?

**Comment by 0r1ce** [comment]
> I can't replicate that issue you're experiencing. Does it happen for specific sites/sources?

It seems the issue is exclusive to Gogoanime(it also seems that loading the menus such as the "recently updated" or "new" have a hard time loading in Gogoanime), it happenes on every show i try to watch.

**Comment by jerry08** [comment]
Can you tell me what version of Android you use and what's the model of your device? I'll be able to check the crash logs with that info.

**Comment by 0r1ce** [comment]
Android 11 and phone model SM-A505F

**Comment by jerry08** [comment]
Hopefully the next update will solve your problem.
