### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by flawlessgoku** [jerry08/AniStream#4]
![Screenshot_2022-09-06-20-53-09](https://user-images.githubusercontent.com/112993329/188765172-affb1ef8-71c0-421d-a695-b33b9ef37f23.png)
Ive updated even from 1.4 to 1.5 and still have bug and loads on forever and never loads

Àlso can you add ability to click on genre anime is and show you anime of same genre

**Comment by jerry08** [comment]
I fixed the issue. Gogoanime updated their site url again. I'll work on finding anime by genre in a future update. I'll mark is as an enhancement.

**Comment by flawlessgoku** [comment]
I will report again just so you know when they change url try adding auto update url feature if possible

**Comment by jerry08** [comment]
Thanks man. I plan to add an auto update url feature as soon as possible. I'll try to add it tomorrow
