### ISSUE TITLE
When you download a episode it wont not even download it,it just create a mp4 file with name of episode number 

### ISSUE THREAD

**Issue by flawlessgoku** [jerry08/AniStream#7]

**Comment by jerry08** [comment]
This happens because I haven't catered for m3u8 streamable links. Some anime in gogoanime (mostly in zoro) only have m3u8 links (streamable and not downloadable unfortunately). I will add validations and try to fix the parsers.

**Comment by jerry08** [comment]
This happens because I haven't catered for m3u8 streamable links. Some anime in gogoanime (mostly in zoro) only have m3u8 links (streamable and not downloadable unfortunately). I will add validations and try to fix the parsers.

**Comment by flawlessgoku** [comment]
Ok thx
